title: "My TIL"
description: "Things I've learned."
url: "https://rocknroll009.github.io"
baseurl: "/til"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
timezone: Asia/Seoul

# GitHub Pages 기본 지원 플러그인(선택)
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"